import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatWidthInch } from "@/lib/utils";
import type { LengthUnit } from "@/generated/prisma/browser";

export interface PatternListData {
  runNumber: string;
  machineName: string;
  maxDeckleInch: number;
  gsm: number;
  createdAt: string | Date;
  unit?: LengthUnit;
  patterns: Array<{
    sequence: number;
    repetitions: number;
    usedWidthInch: number;
    cuts: Array<{
      widthInch: number;
      count: number;
    }>;
  }>;
}

/**
 * Ledger-style pattern list: each pattern is one row showing its constituent
 * cut widths summed ("64.5+30+30"), the total/deckle width, and the
 * repetition count — matching the handwritten cutting-plan format used on
 * the shop floor before this system existed.
 */
function buildPatternListDoc(data: PatternListData): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const displayUnit = (data.unit ?? "INCH") as LengthUnit;
  const fw = (v: number) => formatWidthInch(v, displayUnit);

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  let currentY = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text(`${fw(data.maxDeckleInch)} — ${data.gsm} GSM`, margin, currentY + 6);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Run ${data.runNumber} • ${data.machineName} • ${new Date(data.createdAt).toLocaleDateString("en-IN")}`,
    margin,
    currentY + 12
  );

  currentY += 20;

  // Build each pattern's cut-width breakdown, flattening repeated cut counts
  // into individual addends the way the ledger writes them out (e.g. a cut
  // with count=2 at 30 becomes "30+30").
  const rows = data.patterns.map((pat) => {
    const addends: number[] = [];
    pat.cuts.forEach((c) => {
      for (let i = 0; i < c.count; i++) addends.push(c.widthInch);
    });
    const breakdown = addends.map((w) => fw(w)).join(" + ");
    const total = addends.reduce((s, w) => s + w, 0);
    return [String(pat.sequence), breakdown, `${fw(total)}`, `-${pat.repetitions}`];
  });

  autoTable(doc, {
    startY: currentY,
    head: [["#", "Cut Widths", "Total (Deckle)", "Reps"]],
    body: rows,
    margin: { left: margin, right: margin },
    theme: "grid",
    styles: { font: "helvetica" },
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontSize: 8.5,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [15, 23, 42],
      cellPadding: 3,
      font: "helvetica",
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { halign: "center", cellWidth: 10 },
      1: { cellWidth: 110, fontStyle: "bold" },
      2: { halign: "right", cellWidth: 34, fontStyle: "bold" },
      3: { halign: "center", cellWidth: 20 },
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 8;
  const totalReels = data.patterns.reduce((s, p) => s + p.repetitions, 0);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`Total patterns: ${data.patterns.length}   •   Total reels: ${totalReels}`, margin, finalY);

  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by PaperMill ERP • Deckle Slitter System • Run #${data.runNumber} • Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 5,
      { align: "center" }
    );
  }

  return doc;
}

/** Build the pattern list and trigger a browser download. */
export function generatePatternListPDF(data: PatternListData) {
  buildPatternListDoc(data).save(`PatternList-${data.runNumber}.pdf`);
}

/** Build the pattern list and return it as a PDF Blob (for on-screen viewing). */
export function generatePatternListPDFBlob(data: PatternListData): Blob {
  return buildPatternListDoc(data).output("blob");
}
