"use server";

import { requireRole } from "@/server/auth-helpers";
import { Role } from "@/generated/prisma/browser";

export interface AIExplanationResult {
  summary: string;
  tradeoffs: string;
  suggestions: {
    action: string;
    impact: string;
  }[];
}

export async function explainPlan(planData: {
  machineName: string;
  deckleInch: number;
  gsm: number;
  totalTrimPercent: number;
  totalPlannedKg: number;
  patterns: Array<{
    sequence: number;
    usedWidthInch: number;
    trimWidthInch: number;
    trimPercent: number;
    repetitions: number;
    estimatedKg: number;
    cuts: Array<{
      orderNumber?: string;
      widthInch: number;
      count: number;
    }>;
  }>;
  unassignedCount: number;
}): Promise<AIExplanationResult> {
  await requireRole(Role.ADMIN, Role.PLANNER);

  const apiKey = process.env.ANTHROPIC_API_KEY;

  const promptText = `
You are an expert Paper Mill Production Planning Assistant. Analyze this deckle optimization plan generated by a column-generation LP cutting-stock solver and explain it to the factory planner in simple, professional Hinglish (Roman script). Use real numbers directly from the input. Never hallucinate or invent numbers.

PLAN DATA:
- Machine: ${planData.machineName} (Max Deckle: ${planData.deckleInch}")
- Paper GSM: ${planData.gsm} GSM
- Total Trim Waste: ${planData.totalTrimPercent}%
- Total Planned Output: ${planData.totalPlannedKg.toLocaleString("en-IN")} kg
- Patterns Count: ${planData.patterns.length}
- Patterns Detail:
${planData.patterns
  .map(
    (p) =>
      `  Pattern ${p.sequence}: Cuts [${p.cuts
        .map((c) => `${c.count}x ${c.widthInch}" (${c.orderNumber || "Stock"})`)
        .join(" + ")}], Used: ${p.usedWidthInch}", Trim: ${p.trimWidthInch}" (${p.trimPercent}%), Reps: ${p.repetitions}, Output: ${p.estimatedKg.toLocaleString("en-IN")} kg`
  )
  .join("\n")}
- Unassigned Items: ${planData.unassignedCount}

Respond ONLY with valid JSON having this exact schema:
{
  "summary": "Clear explanation in Hinglish of what this plan achieves on ${planData.machineName} and why this machine fits the ${planData.gsm} GSM run.",
  "tradeoffs": "Detailed explanation in Hinglish of where trim waste occurs, why these cuts were paired, and why leftover trim was mathematically unavoidable.",
  "suggestions": [
    {
      "action": "Specific suggestion in Hinglish with real order/width references",
      "impact": "Estimated trim reduction or kg impact"
    }
  ]
}
`;

  const openaiApiKey = process.env.OPENAI_API_KEY;

  if (openaiApiKey) {
    try {
      const response = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${openaiApiKey}`,
        },
        body: JSON.stringify({
          model: "gpt-4o",
          response_format: { type: "json_object" },
          messages: [
            {
              role: "system",
              content:
                "You are an expert Paper Mill Production Planning Assistant. Analyze this deckle optimization plan generated by a column-generation LP cutting-stock solver and explain it to the factory planner in simple, professional Hinglish (Roman script). Return ONLY valid JSON with keys: summary, tradeoffs, suggestions.",
            },
            {
              role: "user",
              content: promptText,
            },
          ],
        }),
      });

      if (response.ok) {
        const json = await response.json();
        const contentText = json.choices?.[0]?.message?.content || "";
        const parsed = JSON.parse(contentText);
        return parsed as AIExplanationResult;
      }
    } catch (err) {
      console.warn("[AIExplainService] OpenAI API call failed, generating deterministic analysis:", err);
    }
  }

  // Fallback high-fidelity Hinglish explanation engine
  const patternsList = planData.patterns;
  const bestPattern = patternsList.reduce((min, p) => (p.trimPercent < min.trimPercent ? p : min), patternsList[0]);
  const worstPattern = patternsList.reduce((max, p) => (p.trimPercent > max.trimPercent ? p : max), patternsList[0]);

  return {
    summary: `Ye run ${planData.machineName} (${planData.deckleInch}" deckle) par ${planData.gsm} GSM ke liye banaya gaya hai. Total output ${(planData.totalPlannedKg / 1000).toFixed(2)} MT hai jisme average trim waste ${planData.totalTrimPercent}% aaya hai. Machine selection bilkul optimal hai kyunki deckle utilization maximum ho raha hai.`,
    tradeoffs: `Pattern ${bestPattern.sequence} me sabse best fit mila hai (${bestPattern.usedWidthInch}" used, sirf ${bestPattern.trimPercent}% trim). Jabki Pattern ${worstPattern.sequence} me trim thoda zyada (${worstPattern.trimWidthInch}" / ${worstPattern.trimPercent}%) hai kyunki remaining reel widths ka combination exact deckle match nahi kar raha tha.`,
    suggestions: [
      {
        action: `Pattern ${worstPattern.sequence} me ${worstPattern.trimWidthInch}" trim bach raha hai. Iske liye same-GSM ka koi chhota pending order ya stock reel add karke dekhein (neeche Trim Advisor batayega).`,
        impact: `Is pattern ka trim ${worstPattern.trimPercent}% hai, poore run ka ${planData.totalTrimPercent}%.`,
      },
    ],
  };
}
